// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "980a3390-3028-48a6-8d5c-a883c7bcca32");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1618427912);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1618427312);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1618427672);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1618427552);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1618427432);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1618427792);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1618427342);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1618428032);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 144367);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1618427281);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a14d98a1-8d22-40c2-a592-c128ebf40542}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1618429146164");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1618430916164");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1618427297401");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1618448897401");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1618427289");
user_pref("browser.slowStartup.averageTime", 10293);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210119174753");
user_pref("browser.startup.homepage_override.mstone", "78.7.0");
user_pref("browser.startup.lastColdStartupCheck", 1618427286);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.7.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "9753ffdf85294c96a08ad19c1c137fb2");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1618427913);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.7.0");
user_pref("extensions.lastPlatformVersion", "78.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"514221e3-263e-4c02-a29d-a59c1275f120\",\"formautofill@mozilla.org\":\"d4b69683-9bdf-4065-897d-703cb7971109\",\"screenshots@mozilla.org\":\"065ca833-e723-4b73-95a7-f3b432d159d5\",\"webcompat-reporter@mozilla.org\":\"154f9081-9bf3-4526-8c83-2c72b2983838\",\"webcompat@mozilla.org\":\"7511e797-4993-4e18-a10a-03e71c87fe4a\",\"default-theme@mozilla.org\":\"fefed806-b3e4-420d-b410-7222a315852d\",\"google@search.mozilla.org\":\"4583684e-3e9b-4166-b210-b928d75c6752\",\"amazondotcom@search.mozilla.org\":\"54791f02-ef27-45ae-93a8-e7c8799f8952\",\"wikipedia@search.mozilla.org\":\"2b19fe26-0160-4288-8920-12229f010458\",\"bing@search.mozilla.org\":\"11ffae15-be2b-4c03-b49b-ef822d534416\",\"ddg@search.mozilla.org\":\"463d2731-b4e0-49ac-9dc9-2a401a28d684\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1618427917);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20210119174753");
user_pref("media.gmp-manager.lastCheck", 1618429279);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 94719);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "4a699c3c-c44c-4db7-ae78-e0530cb8c2f9");
user_pref("security.sandbox.plugin.tempDirSuffix", "8eab08ed-494c-4b27-b14c-4b4295dba347");
user_pref("services.blocklist.addons-mlbf.checked", 1618427792);
user_pref("services.blocklist.gfx.checked", 1618427792);
user_pref("services.blocklist.plugins.checked", 1618427792);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1618425472068\"");
user_pref("services.settings.last_update_seconds", 1618427792);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1618427792);
user_pref("services.settings.main.cfr-fxa.last_check", 1618427792);
user_pref("services.settings.main.cfr.last_check", 1618427792);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1618427792);
user_pref("services.settings.main.hijack-blocklists.last_check", 1618427792);
user_pref("services.settings.main.language-dictionaries.last_check", 1618427792);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1618427792);
user_pref("services.settings.main.search-config.last_check", 1618427792);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1618427792);
user_pref("services.settings.main.sites-classification.last_check", 1618427792);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1618427792);
user_pref("services.settings.main.whats-new-panel.last_check", 1618427792);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1618427276);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210119174753");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
